# Generated by Django 5.0.4 on 2024-06-19 07:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sportovec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(help_text='Zadejte jméno sportovce', max_length=80, verbose_name='Jméno sportovce')),
                ('prijmeni', models.CharField(help_text='Zadejte jméno sportovce', max_length=80, verbose_name='Příjmení spoertovce')),
                ('narodnost', models.CharField(help_text='Zadejte národnost sportovce', max_length=50, verbose_name='Národnost sportovce')),
                ('narozeni', models.DateField(blank=True, null=True, verbose_name='Datum narození sportovce')),
                ('vaha', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(35)], verbose_name='Váha sportovce v kg')),
                ('vyska', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(130)], verbose_name='Výška sportovce v cm')),
            ],
            options={
                'verbose_name': 'Sportovec',
                'verbose_name_plural': 'Sportovci',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Tym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='Název týmu')),
                ('sport', models.CharField(max_length=50, verbose_name='Název sportu')),
                ('zalozeni', models.DateField(blank=True, null=True, verbose_name='Datum založení týmu')),
            ],
            options={
                'verbose_name': 'Tým',
                'verbose_name_plural': 'Tým',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Akce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum konání')),
                ('cas', models.TimeField(verbose_name='čas konání')),
                ('misto', models.CharField(max_length=100, verbose_name='Místo konání')),
                ('ucastnici', models.ManyToManyField(to='app.sportovec')),
            ],
            options={
                'verbose_name': 'Datum konání',
                'verbose_name_plural': 'Datum konání',
                'ordering': ['datum'],
            },
        ),
        migrations.AddField(
            model_name='sportovec',
            name='tym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tym', verbose_name='Tým sportovce'),
        ),
    ]
